research_task:
  description: "Use the SerperDevTool to find the most relevant and recent data on {topic}."
  assigned_agent: "research_agent"
  expected_output: "A detailed research report with key insights and source references."

summarization_task:
  description: "Summarize the research findings into a well-structured, concise report."
  assigned_agent: "summarization_agent"
  expected_output: "A summary highlighting the key takeaways from the research."
  depends_on: "research_task"

fact_checking_task:
  description: "Cross-check the summarized information for accuracy and remove any misleading claims."
  assigned_agent: "fact_checker_agent"
  expected_output: "A fact-checked and verified research summary."
  depends_on: "summarization_task"